### PR TITLE
Array Setter tests

### PR DESCRIPTION
**Pull request by YOzaz**
To debug our code further, I've made two tests you can use.

### CODE REVIEW

**Comment by YOzaz** [comment]
Actualy, I just checked again - your patch is working how I was expecting.
```php
// Config::get
array (size=1)
  'ctr' => float 0.01
// Setting::get
array (size=1)
  'ctr' => string '0.01' (length=4)
```
Ideally it should auto-case to correct types as well, but that's json decoding issue?
As for tests I have created - not sure if your package is compatible with storing arrays ;) you can ignore this pull request.

**Comment by bradcornford** [comment]
Yeah, i noticed the type issue. I'll have a look into that now.

As for storing array, it should be work as expected too:

```php
    var_dump(Config::get('services.mandrill'));
    var_dump(Setting::get('services.mandrill'));
    var_dump(Setting::set('services.mandrill.secret', [1,2,3]));
    var_dump(Setting::get('services.mandrill'));
    var_dump(Setting::get('services.mandrill.secret'));
```

Outputs:

```
array (size=1)
  'secret' => string '' (length=0)

array (size=1)
  'secret' => string '' (length=0)

boolean true

array (size=1)
  'secret' => 
    array (size=3)
      0 => int 1
      1 => int 2
      2 => int 3

array (size=3)
  0 => int 1
  1 => int 2
  2 => int 3

```

**Comment by bradcornford** [comment]
Just tested the type issue too, and can't seem to replicate:

```php
    var_dump(Config::get('services.mandrill'));
    var_dump(Setting::get('services.mandrill'));
    var_dump(Setting::set('services.mandrill.secret', 0.01));
    var_dump(Setting::get('services.mandrill'));
    var_dump(Setting::get('services.mandrill.secret'));
```

Output:

```
array (size=1)
  'secret' => string '' (length=0)

array (size=1)
  'secret' => string '' (length=0)

boolean true

array (size=1)
  'secret' => float 0.01

float 0.01

```

**Comment by YOzaz** [comment]
Strange... I can't either on different PC. Something related to PHP settings?
Anyway, I think it can be released. Good job!

**Comment by bradcornford** [comment]
Yeah it could be, not entirely sure if I'm honest. I would expect the json method's to be the same on any version.

It's now merged to master under version 1.5.2.

**Comment by YOzaz** [comment]
Found it - mistake on my side. Passed as a string to Setter, as that's how PHP returns submitted form field values. Strangely enough, I"m pretty sure behaviour is different with Firefox and Chrome.
Anyway - not related to the package, it shouldn't check if overwritten Config values are same type, neither do type casting (I think).

**Comment by bradcornford** [comment]
Ah that explains it, I think all browsers will actually send strings when posting / receiving data.

Okay, I think your right on the type casting, it already casts back to whatever you save, so trying t detect types could become messy.

Thanks for you help in resolving this issue.

**Pull request closed without merging**
